STAR --genomeDir ${index} \\
--sjdbGTFfile $gtf \\
--readFilesIn $reads \\
--runThreadN ${task.cpus} \\
--outFileNamePrefix '${sampleid}.' \\
--outFilterType ${params.star_mapping.outFilterType} \\
--outSAMtype ${params.star_mapping.outSAMtype} \\
--outWigType ${params.star_mapping.outWigType} \\
--alignEndsType EndToEnd \\
--outFilterMismatchNmax 3 \\
--outFilterMultimapScoreRange 0 \\
--outFilterMultimapNmax 20 \\
--outSAMunmapped Within \\
--outFilterScoreMinOverLread 0 \\
--outFilterMatchNminOverLread 0 \\
--outFilterMatchNmin 16 \\
--alignSJDBoverhangMin 1000 \\
--alignIntronMax 1
